### ISSUE TITLE
Customer -> Customer Contacts

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#10]
As a user of the application, I should be able to view the customer's contacts of a specific customer

Acceptance Criteria:

1. In customer contacts tab, only respective customer contacts should be displayed.
Example – In the above image, contacts which belong to American Wood Mark will be displayed.

2. If a new contact is added from here, then the contact will be added to American Wood Mark Company and will also be displayed in the Master contact module.

3. No other than American Wood Mark Company contacts will be displayed here.

4. DC Location contacts (company level contact) will come from customer contacts tab and user can add new contacts like Driver, a warehouse manager from the DC location tab child grid and the contact will be added to Master contact module, these contacts will not appear in the customer contact tab.

5. Company level contacts will be able to see all the jobs assigned to the DC location
If a contact is added to DC – Location then the contact/user can view only those jobs which are mapped to that location.

6 Code will filter based on Customer Ref Roles.

Definition of Done
1. All mandatory fields should be filled and saved.
2. Should pass regression test and unit testing.
3. Pass testing as per acceptance criteria.

**Comment by kirtya** [comment]
Update SP to only contact which has type customer

**Comment by kirtya** [comment]
Update SP to get only Contact has been added to customer/vendor for DC Location contact

**Comment by kirtya** [comment]
Code changes has been done to get current company id of customer or vendor while creating new customer/vendor contact, as well as for dclocation contacts
