### ISSUE TITLE
M4PL API Does Not Populate Gateway Dates

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#107]
When calling the M4PL API UpdateJobAttributes method the gateways that are created have blank Planned and Baseline Completed Dates.

**Comment by nmfujimoto** [comment]
![image](https://user-images.githubusercontent.com/50392020/68434406-bbad9600-016d-11ea-8de8-a14b4e40c6ae.png)

**Comment by kirtya** [comment]
Hi @nmfujimoto ,

Issue has been fixed and updated in 1010 and 3030 server.

Issue was due to copy of default gateways while creating the job.
