### ISSUE TITLE
M4PL NAV Not Syncing Default Cost Rates

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#108]
When syncing Cost rates in M4PL the default rates are not updated. This might have to do with how rates are assigned and what is retrieved through the web service.

**Comment by nmfujimoto** [comment]
NAV Item List showing the 44SCDEL record that is used as a default delivery rate for AWC Selling Center Program.
![image](https://user-images.githubusercontent.com/50392020/68437873-2b744e80-0177-11ea-9d7a-9c34e2d79ea5.png)

Clicking on the Cost Codes tab for the AWC Selling Center displays a $0 rate.
![image](https://user-images.githubusercontent.com/50392020/68437920-565ea280-0177-11ea-89be-6e56d0670f72.png)

Clicking on the Price Codes tab for the AWC Selling Center displays the expected $175 rate. 
![image](https://user-images.githubusercontent.com/50392020/68437954-6aa29f80-0177-11ea-855f-7c3675bc56d4.png)

**Comment by nmfujimoto** [comment]
Can we retrieve the Cost Rate when no vendor is assigned? This functionality is needed for all default rates for Cost Codes. There will be no vendor assigned since they are defaults and not location rates.

**Comment by prashantaggarwal1999** [comment]
Hi Nathan, Rates which are returning from NAV are passing the VendorId which application is using to update the cost rate by matching code and VendorId. There are no rates coming from NAV for default rate with VendorId as null or 0. NAV response is as follows:

{
  "@odata.context": "https://nav.meridianww.com:7048/DEV/ODataV4/$metadata#Company('Meridian')/PurchasePrices",
  "value": [
    {
      "@odata.etag": "W/\"JzEzMjtaQnNBQUFKNy96UUFOQUJCQUV3QVFnQkJBRXdBUWdCT0FFMEFTQUJFQUVRQVJRQk1BQUFBQW5zRk9BQXdBREFBTVFBM0FBQUFBQzRBQUFBQUFuc0FBQUFDZXdBQUFBSjcvMUFBUXdCVEFBQUFBRElBQUFBQUFBQUFBQUFBQUFBQUFBPT04OzEwNTcxMTc2MDsn\"",
      "Item_No": "44ALBALBNMHDDEL",
      "Vendor_No": "80017",
      "Starting_Date": "0001-01-01",
      "Currency_Code": "",
      "Variant_Code": "",
      "Unit_of_Measure_Code": "PCS",
      "Minimum_Quantity": 0,
      "VendNoFilterCtrl": "",
      "ItemNoFIlterCtrl": "",
      "StartingDateFilter": "",
      "Direct_Unit_Cost": 18,
      "Ending_Date": "0001-01-01"
    },
    {
      "@odata.etag": "W/\"JzEzMjtaQnNBQUFKNy96UUFOQUJCQUUwQVVBQk5BRThBVWdCVUFFNEFTQUJFQUVRQVJRQk1BQUFBQW5zRk9BQXdBREVBTXdBMUFBQUFBQzRBQUFBQUFuc0FBQUFDZXdBQUFBSjcvMUFBUXdCVEFBQUFBRElBQUFBQUFBQUFBQUFBQUFBQUFBPT04OzEwNTQ1NDUyMDsn\"",
      "Item_No": "44AMPMORTNHDDEL",
      "Vendor_No": "80135",
      "Starting_Date": "0001-01-01",
      "Currency_Code": "",
      "Variant_Code": "",
      "Unit_of_Measure_Code": "PCS",
      "Minimum_Quantity": 0,
      "VendNoFilterCtrl": "",
      "ItemNoFIlterCtrl": "",
      "StartingDateFilter": "",
      "Direct_Unit_Cost": 0,
      "Ending_Date": "0001-01-01"
    },
    {
      "@odata.etag": "W/\"JzEzMjtaQnNBQUFKNy96UUFOQUJGQUV3QVRBQlBBRXdBUkFCVUFFNEFTQUJFQUVRQVJRQk1BQUFBQW5zRk9BQXdBREVBTVFBMEFBQUFBQzRBQUFBQUFuc0FBQUFDZXdBQUFBSjcvMUFBUXdCVEFBQUFBRElBQUFBQUFBQUFBQUFBQUFBQUFBPT04OzEwNjE2NTQwMDsn\"",
      "Item_No": "44ELLOLDTNHDDEL",
      "Vendor_No": "80114",
      "Starting_Date": "0001-01-01",
      "Currency_Code": "",
      "Variant_Code": "",
      "Unit_of_Measure_Code": "PCS",
      "Minimum_Quantity": 0,
      "VendNoFilterCtrl": "",
      "ItemNoFIlterCtrl": "",
      "StartingDateFilter": "",
      "Direct_Unit_Cost": 11,
      "Ending_Date": "0001-01-01"
    },
    {
      "@odata.etag": "W/\"JzEzMjtaQnNBQUFKNy96UUFOQUJLQUVVQVZBQlRBRkFBVHdCWEFFRUFTQUJFQUVRQVJRQk1BQUFBQW5zRk9BQXdBREVBTkFBeUFBQUFBQzRBQUFBQUFuc0FBQUFDZXdBQUFBSjcvMUFBUXdCVEFBQUFBRElBQUFBQUFBQUFBQUFBQUFBQUFBPT04OzEwNjE2NTg2MDsn\"",
      "Item_No": "44JETSPOWAHDDEL",
      "Vendor_No": "80142",
      "Starting_Date": "0001-01-01",
      "Currency_Code": "",
      "Variant_Code": "",
      "Unit_of_Measure_Code": "PCS",
      "Minimum_Quantity": 0,
      "VendNoFilterCtrl": "",
      "ItemNoFIlterCtrl": "",
      "StartingDateFilter": "",
      "Direct_Unit_Cost": 11.75,
      "Ending_Date": "0001-01-01"
    },
    {
      "@odata.etag": "W/\"JzEzMjtaQnNBQUFKNy96UUFOQUJPQUVVQVZ3QkNBRWtBVWdCQkFFd0FTQUJFQUVRQVJRQk1BQUFBQW5zRk9BQXdBREVBTkFBeEFBQUFBQzRBQUFBQUFuc0FBQUFDZXdBQUFBSjcvMUFBUXdCVEFBQUFBRElBQUFBQUFBQUFBQUFBQUFBQUFBPT04OzEwNTU2NDIzMDsn\"",
      "Item_No": "44NEWBIRALHDDEL",
      "Vendor_No": "80141",
      "Starting_Date": "0001-01-01",
      "Currency_Code": "",
      "Variant_Code": "",
      "Unit_of_Measure_Code": "PCS",
      "Minimum_Quantity": 0,
      "VendNoFilterCtrl": "",
      "ItemNoFIlterCtrl": "",
      "StartingDateFilter": "",
      "Direct_Unit_Cost": 12.5,
      "Ending_Date": "0001-01-01"
    },
    {
      "@odata.etag": "W/\"JzEyNDtaQnNBQUFKNy96WUFOZ0JLQUVVQVZBQldBRVVBVWdCREFFRUFTQUJFQUVRQVJRQk1BQUFBQW5zRk9BQXdBREFBT0FBeUFBQUFBQzRBQUFBQUFuc0FBQUFDZXdBQUFBSjdBQUFBQURJQUFBQUFBQUFBQUFBQUFBQUFBQT09ODsxMDYxNjY0NTA7Jw==\"",
      "Item_No": "66JETVERCAHDDEL",
      "Vendor_No": "80082",
      "Starting_Date": "0001-01-01",
      "Currency_Code": "",
      "Variant_Code": "",
      "Unit_of_Measure_Code": "",
      "Minimum_Quantity": 0,
      "VendNoFilterCtrl": "",
      "ItemNoFIlterCtrl": "",
      "StartingDateFilter": "",
      "Direct_Unit_Cost": 10.25,
      "Ending_Date": "0001-01-01"
    },
    {
      "@odata.etag": "W/\"JzEzMjtaQnNBQUFKNy96Y0FOd0JCQUV3QVFnQkJBRXdBUWdCT0FFMEFTQUJFQUVRQVJRQk1BQUFBQW5zRk9BQXdBREFBTVFBM0FBQUFBQzRBQUFBQUFuc0FBQUFDZXdBQUFBSjcvMUFBUXdCVEFBQUFBRElBQUFBQUFBQUFBQUFBQUFBQUFBPT04OzEwNTcxMzExMDsn\"",
      "Item_No": "77ALBALBNMHDDEL",
      "Vendor_No": "80017",
      "Starting_Date": "0001-01-01",
      "Currency_Code": "",
      "Variant_Code": "",
      "Unit_of_Measure_Code": "PCS",
      "Minimum_Quantity": 0,
      "VendNoFilterCtrl": "",
      "ItemNoFIlterCtrl": "",
      "StartingDateFilter": "",
      "Direct_Unit_Cost": 18,
      "Ending_Date": "0001-01-01"
    },
    {
      "@odata.etag": "W/\"JzEzMjtaQnNBQUFKNy96Y0FOd0JDQUVVQVFRQlVBRlVBVEFCUEFFc0FTQUJFQUVRQVJRQk1BQUFBQW5zRk9BQXdBREFBTmdBMEFBQUFBQzRBQUFBQUFuc0FBQUFDZXdBQUFBSjcvMUFBUXdCVEFBQUFBRElBQUFBQUFBQUFBQUFBQUFBQUFBPT04OzEwNjE2NzMzMDsn\"",
      "Item_No": "77BEATULOKHDDEL",
      "Vendor_No": "80064",
      "Starting_Date": "0001-01-01",
      "Currency_Code": "",
      "Variant_Code": "",
      "Unit_of_Measure_Code": "PCS",
      "Minimum_Quantity": 0,
      "VendNoFilterCtrl": "",
      "ItemNoFIlterCtrl": "",
      "StartingDateFilter": "",
      "Direct_Unit_Cost": 13,
      "Ending_Date": "0001-01-01"
    },
    {
      "@odata.etag": "W/\"JzEzMjtaQnNBQUFKNy96Y0FOd0JLQUVVQVZBQlRBRkFBVHdCWEFFRUFTQUJFQUVRQVJRQk1BQUFBQW5zRk9BQXdBREVBTkFBeUFBQUFBQzRBQUFBQUFuc0FBQUFDZXdBQUFBSjcvMUFBUXdCVEFBQUFBRElBQUFBQUFBQUFBQUFBQUFBQUFBPT04OzEwNjE2Nzg4MDsn\"",
      "Item_No": "77JETSPOWAHDDEL",
      "Vendor_No": "80142",
      "Starting_Date": "0001-01-01",
      "Currency_Code": "",
      "Variant_Code": "",
      "Unit_of_Measure_Code": "PCS",
      "Minimum_Quantity": 0,
      "VendNoFilterCtrl": "",
      "ItemNoFIlterCtrl": "",
      "StartingDateFilter": "",
      "Direct_Unit_Cost": 11.75,
      "Ending_Date": "0001-01-01"
    }
  ]
}

**Comment by nmfujimoto** [comment]
Prashant,
Thank you for the confirmation that the default rates are not seen when retrieving Purchase Price items. We will need to ask Sainath if there is a way to retrieve the NAV Items list (first image in my original post) and match on the Item No. field which is M4PL Cost Code. If we can retrieve the entire Items list than the Cost value should be available (again, based upon what I see in the first image). I am not sure if we have a NAV web service call to retrieve all Items (don't see that web method in my notes) so we will need Sainath to research and see if there is a web service call for that.
