### ISSUE TITLE
Job Price/Cost Tabs Showing Multiple Charges

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#109]
Trying to add Charges to the Job Price/Cost tabs display multiple records for the same charge. This is most likely caused by removing the location from the Program Price/Cost tabs and re-assigning the location (to refresh the Location Code) in the Price/Cost tab. When the location is removed and added in the Program Price/Cost tabs the Charge records under the location are not displayed again so the user must create new Charge records for the location.

**Comment by nmfujimoto** [comment]
Example in 1010, I removed and re-assigned the Pacific Storage Sacramento location to refresh the correct Location code at the Program module for the Price/Cost tabs to setup SACRAMENTO CA vendor location. When selecting a Job assigned to SACRAMENTO CA site code (vendor location code) in the Price tab for the Job there are 3 Delivery Charge records. We need to decide if we display the existing records for the location or delete the records when we un-assign the vendor location in the Program Price/Cost tabs. 

![image](https://user-images.githubusercontent.com/50392020/68504843-d1c56000-021a-11ea-9268-dd4ddc890b69.png)

Selecting each Delivery Charge shows that they are individual records with different Charge ID values. 
![image](https://user-images.githubusercontent.com/50392020/68504880-e73a8a00-021a-11ea-90c5-7bc11e756d14.png)

![image](https://user-images.githubusercontent.com/50392020/68504885-eace1100-021a-11ea-8b4d-cb16b9edd2fb.png)

![image](https://user-images.githubusercontent.com/50392020/68504898-ee619800-021a-11ea-91e3-a7a0373c8f81.png)

**Comment by prashantaggarwal1999** [comment]
Hi Nathan, When the user is deleting the location then it's corresponding charges are not getting deleted which was causing this issue. There were three charges present for the location SACRAMENTO CA in charge table, all of them had a different locationId. While getting the charges application was not using the active/inactive for location, only for charge this condition was there. The condition has been added now and it is working as expected. Please let us know if you will see this Behaviour again.

**Comment by nmfujimoto** [comment]
Prashant,

Thank you for the update. I will test and let the team know if I encounter any new issues.

Thank you,

Nathan Fujimoto
nfujimoto@meridianww.com<mailto:nfujimoto@meridianww.com>
Business: (951) 268-2190
Cell: (951) 616-9271

[fm_meridian_branding_logo_filled_small_v1]
