### ISSUE TITLE
CR - Contacts mapping to a Program/Project/Phase/Jobs

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#11]
As a user of the application, I should be able to view those contact which is relevant to the Program/Project/Phase/Jobs

Acceptance Criteria:
1. Contacts will come from respective customer contacts (AWC), M4PL employee and mapped Vendors contacts.
2. Only one customer company contacts can be mapped to a Program/Project/Phase/Jobs
3. Multiple Vendors can be mapped to a  Program/Project/Phase/Jobs

(Example – Only AWC contacts will appear in AWC  Program/Project/Phase/Jobs, MBC contacts cannot be added to this Program/Project/Phase/Jobs)

Definition of Done

1. All mandatory fields should be filled and saved.
2. Should pass regression test and unit testing.
3. Pass testing as per acceptance criteria.

**Comment by ChauhanNikhil** [comment]
Implemented as per  requirement and  description

**Comment by ChauhanNikhil** [comment]
Created Sps to  filter to mapped  contacts based on Contact roles
