### ISSUE TITLE
Advanced Filter On Job Screen Throwing Error

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#118]
In both instances, 1010 and 3030 the Advance Filter throws an error and displays the "Under Construction" screen. I tried a filter using Site Code for two locations, e.g. OR operator and Site Code as "Stockton" and Site Code "San Marcos" for the filtering.

**Comment by prashantaggarwal1999** [comment]
Changes have been made for this and pushed to 1010.
