### ISSUE TITLE
The URL m4pl.meridianww.com redirects to m4pl.meridianww.com/survey

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#122]
Why is the URL m4pl.meridianww.com redirecting to m4pl.meridianww.com/survey? The m4pl.meridianww.com URL should redirect to the Production instance (3030) for M4PL. The surveys should use the survey.meridianww.com URL.

**Comment by prashantaggarwal1999** [comment]
This issue has been corrected.
