### ISSUE TITLE
The Program Default Gateway Completed check box is read-only and should be editable.

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#123]
The new Program Default Gateway check box should be editable in the Form view and Grid view (batch saving mode).

**Comment by nmfujimoto** [comment]
![image](https://user-images.githubusercontent.com/50392020/74860429-77e63300-52fd-11ea-9e8c-ae439a0b358c.png)

**Comment by prashantaggarwal1999** [comment]
Hi @nmfujimoto, Changes have been done for this and it is working now in 1010.
