### ISSUE TITLE
Update Customer ERP ID in M4PL application from NAV

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#13]
As a user of the application, I should be able to view the customer ERP ID.

Business rules -

1. Place Sync Customer button under the administration  tab on the ribbon
2. On Click of "Sync Customer" button, call NAV web service and retrieve NAV customer records
3. Start Looping Through M4PL Customers And Find Matching NAV Customers (One-To-One Record)
4. Batch Update M4PL Customer ERP ID Fields With Matching NAV Customers (Updates All One-To-One Record)
5. Loop Through all the One-To-Many Records
6. Display a single pop up screen to show One-To-Many Customer Records Found For User To Select Correct NAV Customer
7. Update ERP ID For One-To-Many Customer

Different scenarios in One-To-Many 

a.	First Would Be AWC is One-To-One -> Assign NAV ERP ID to M4PL Customer AWC

b.	Next Customer, MasterBrand Is One-To-Many 
1.	MasterBrand
2.	MasterBrand Canada
ii.	Display Dialog Screen Asking User To Select Correct NAV Customer Record
iii.	User Selects Correct NAV Customer and Clicks OK
iv.	Assign NAV ERP ID to M4PL Customer MasterBrand Based On User Selection From Step iii

c.	Next Customer, DreamOrbit Furniture
i.	No NAV Customer Record Found - Leave ERP ID In M4PL Blank
ii.     If NAV customer Record Found - Update the ERP ID in M4PL

Acceptance Criteria:
1. Customer ERP ID should be updated if it's present in NAV
2. Customer ERP ID should be left blank if it's not present in NAV

Definition of Done
1.  All mandatory fields should be filled and saved.
2. Should pass regression test and unit testing.
3. Pass testing as per acceptance criteria.

NAV Links

SOAP
https://nav.meridianww.com:7047/DEV/WS/Meridian/Page/CustomerList

OData
https://nav.meridianww.com:7048/DEV/OData/Company('Meridian')/CustomerList

**Comment by prashantaggarwal1999** [comment]
Model creation as per Nav API Response for Vendor and Customer Data and write logic to get the data from Nav and stored.

**Comment by prashantaggarwal1999** [comment]
Write the code to compare the existing M4PL Customer data with Nav Customer List and map the ERPId.

**Comment by kirtya** [comment]
Introduce new button on top nav bar to sync customer and sync vendor ERP ID from NAV api response.

**Comment by kirtya** [comment]
Created Popup view to compare the M4PL customer with NAV match result for selecting of appropriate ERP ID

**Comment by kirtya** [comment]
Write Logic to redirect to customer and vendor data view as respective to sync operation once all matches has been updated.

**Comment by kirtya** [comment]
Write logic to handle the popup functional scenario for close, save, if not available of matches data.
