### ISSUE TITLE
Display master-detail grid in Program/project/phase/Jobs -> Price codes and Cost codes

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#15]
As a user of the application, I should be able to view the price codes and cost codes in program and jobs as per the location.

Business Rules,
1. Implement master-detail grid grouping by Location in Program-> Price codes
2. Implement master-detail grid grouping by Location in Program-> Cost codes
3. Implement master-detail grid grouping by Location in Project-> Price codes
4. Implement master-detail grid grouping by Location in Project-> Cost codes
5. Implement master-detail grid grouping by Location in Phase -> Price codes
6. Implement master-detail grid grouping by Location in Phase -> Cost codes
7. Implement master-detail grid grouping by Location in Jobs (program)-> Price codes
8. Implement master-detail grid grouping by Location in Jobs (Program) -> Cost codes
9. Implement master-detail grid grouping by Location in Jobs (project)-> Price codes
10. Implement master-detail grid grouping by Location in Jobs (project) -> Cost codes
11. Implement master-detail grid grouping by Location in Jobs (phase)-> Price codes
12. Implement master-detail grid grouping by Location in Jobs (phase) -> Cost codes

Definition of Done
Check only for the UI

Note -
1.  Mockup attached only for the program, it will be same for projects and phase
2.  Add master-detail grid under Jobs->Price/Cost tabs
3. Under price codes tab, master grid fields - ProgramID, VendorID, Location Code, Location code Customer, Location Title, Code1, Code 2, Code 3, Code 4, Code 5, Entered By,  Date Entered, Changed By and Date Changed  (This might change later)
Child grid fields - ID, code, customer code, title, billable price, and category (This might change later)
4. Under Cost Codes tab, master grid Fields - ProgramID, VendorID, Location Code, Location code Customer, Location Title, Code1, Code 2, Code 3, Code 4, Code 5, Entered By,  Date Entered, Changed By and Date Changed(This might change later)
Child grid fields - ID, code, Vendor code, title cost rate (This might change later)

**Comment by nmfujimoto** [comment]
As a user of the application, I should be able to view the price codes and cost codes in program and jobs as per the location.

Business Rules,
1. Implement master-detail grid grouping by Location in Program-> Price codes
2. Implement master-detail grid grouping by Location in Program-> Cost codes
3. Implement master-detail grid grouping by Location in Project-> Price codes
4. Implement master-detail grid grouping by Location in Project-> Cost codes
5. Implement master-detail grid grouping by Location in Phase -> Price codes
6. Implement master-detail grid grouping by Location in Phase -> Cost codes
7. Implement master-detail grid grouping by Location in Jobs (program)-> Price codes
8. Implement master-detail grid grouping by Location in Jobs (Program) -> Cost codes
9. Implement master-detail grid grouping by Location in Jobs (project)-> Price codes
10. Implement master-detail grid grouping by Location in Jobs (project) -> Cost codes
11. Implement master-detail grid grouping by Location in Jobs (phase)-> Price codes
12. Implement master-detail grid grouping by Location in Jobs (phase) -> Cost codes

Definition of Done
Check only for the UI

Note -
1.  Mockup attached only for the program, it will be same for projects and phase
2.  Add master-detail grid under Jobs->Price/Cost tabs
3. Under price codes tab, master grid fields - ProgramID, VendorID, Location Code, Location code Customer, Location Title, Code1, Code 2, Code 3, Code 4, Code 5, Entered By,  Date Entered, Changed By and Date Changed  (This might change later)
Child grid fields - ID, code, customer code, title, billable price, and category (This might change later)
4. Under Cost Codes tab, master grid Fields - ProgramID, VendorID, Location Code, Location code Customer, Location Title, Code1, Code 2, Code 3, Code 4, Code 5, Entered By,  Date Entered, Changed By and Date Changed(This might change later)
Child grid fields - ID, code, Vendor code, title cost rate (This might change later)

**Comment by ChauhanNikhil** [comment]
Created PrgCostLocation and PrgBillableLocation tables
