### ISSUE TITLE
Company name in the contact pop up card should come from organization/Customer/Vendor company name

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#17]
As a user of the application, I should be able to assign contact to an organization/Customer/Vendor company name.

Business Rules,

1. Administration Module ->System accounts

Contact pop up card, the company name will be a drop-down and the values will come from the organization, customer and vendor and Type (drop-down) will be 

Case -1 If the company name selected is organization then the type will be - Employee, Contractor, consultant
Case -2  If the company name selected is Customer then the type will be - Customer, Driver
Case -3  If the company name selected is Vendor then the type will be - Vendor, Driver

The corporate address will be populated in the address field based on the company name

The following fields will be entered by the user, Title, First name, Middle Name, Last Name, Job Title, Business phone, Phone Extension, Mobile Phone, Type, work email and Individual email/System.

2. Jobs - Driver details

Contact pop up card, the company name will be a drop-down and the values will come from the  mapped vendor and type will be the driver (read Only)

Case -1  If the company name selected is Vendor then the type will be -  Driver

The corporate address will be populated in the address field based on the company name

The following fields will be entered by the user, Title, First name, Middle Name, Last Name, Job Title, Business phone, Phone Extension, Mobile Phone, Type, work email and Individual email/System,

Note -

On the contact pop up card, rename the field -> Organisation name to Company name

**Comment by prashantaggarwal1999** [comment]
Create the table for Company which will store the Customer, Vendor and Organization with entity type. Populate the data for the company from different entities. Fetch the data for the company and show the dropdown list.
