### ISSUE TITLE
Change the company Name text field to Drop down value

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#19]
As a user of the application, I should be able to select the company name for the organization, vendor or customer

Business rules - (Assumption - Company/Customer/vendor are active)

1. Change the contact master- Company name text field to drop down value

2. The contact master- Company name value will come from the Organisation/customer/Vendor module (Only active Company/Customer/vendor names )

3. Based on the company selected in the contact master, the drop-down values will change in the Type field. 

Case -1 If the company name selected is organization then the type will be - Employee, Contractor, consultant
Case -2  If the company name selected is Customer then the type will be - Customer, Driver
Case -3  If the company name selected is Vendor then the type will be - Vendor, Driver

Point 4,5 and 6 are implemented and they are added here for reference
4. To add company name - Go to organization module click on new (ribbon), add the details and save it 
5. To add Customer company name - Go to customer module, right click -> new, add the details and click on save to save the entered details.
6. To add Vendor company name - Go to Vendor module, right click -> new, add the details and click on save to save the entered details. 

7. Address fields in Customer->Address->Corporate Address will be editable.
Replace the address field by the following fields - Corporate Address Line 1, Corporate Address Line 2, Corporate  City,  Corporate State province, Corporate Zip postal and Corporate Country Region. 

8. Address fields in Customer->Address->Business Address will be editable
Replace the address field by the following fields - Business Address Line 1, Business Address Line 2, Business City,  Business State province, Business Zip postal and Business  Country Region. 

9. Address fields in Customer->Address->Work Address will be editable
Replace the address field by the following fields -  Work Address Line 1, Work Address Line 2, Work City,  Work  State province, Work Zip postal and Work Country Region. 

10. Address fields in Vendor ->Address->Corporate Address will be editable
Replace the address field by the following fields -  Corporate Address Line 1, Corporate Address Line 2, Corporate  City,  Corporate State province, Corporate Zip postal and Corporate Country Region. 

11. Address fields in Vendor ->Address->Business Address will be editable
Replace the address field by the following fields - Business Address Line 1, Business Address Line 2, Business City,  Business State province, Business Zip postal and Business  Country Region. .

12. Address fields in Vendor ->Address->Work Address will be editable
Replace the address field by the following fields - Remove/update the address field and add the following fields Work Address Line 1, Work Address Line 2, Work City,  Work  State province, Work Zip postal and Work Country Region.

13. In Customer->Address ->Corporate Address/Business Address/Work Address, based on the contact selected in the contact drop down, the Full name, business phone, and work email will be populated in Corporate Address/Business Address/Work Address respectively

14.  In Vendor->Address->Corporate Address/Business Address/Work Address, based on the contact selected in the contact drop down, the Full name, business phone, and work email will be populated in Corporate Address/Business Address/Work Address respectively

15. Company Name in (Master contact) Contact Data View Screen will be a NON MANDATORY field.

16. Title in Customer Data View Screen, Vendor Data View Screen and Organization Data View Screen is going to be a UNIQUE field 

17. The contacts which are assigned to a specific company/vendor/customer will appear in the contact dropdown when a user is selecting a contact. . 

Ex- If Contact A, B, C, and E are assigned to AWC customer in contact master, then in customer contact when a user is adding a new contact, contact A, B, C and E will appear in the contact drop down, If contact D is assigned to MB customer in Contact master, then in customer contact of MB, when a user is adding a new contact, contact D will appear in the drop-down.  . 

Acceptance Criteria:

1. Check for all the above business rules.

Definition of Done
1. All mandatory fields should be filled and saved.
2. Should pass regression test and unit testing.
3. Pass testing as per acceptance criteria

Note -

On the contact pop up card, rename the field -> Organisation name to Company name

**Comment by prashantaggarwal1999** [comment]
Create the Partial View For Company Drop down.

**Comment by prashantaggarwal1999** [comment]
Create the table for Company which will store the Customer, Vendor and Organization with entity type.

**Comment by prashantaggarwal1999** [comment]
Populate the companyId from the existing entities, update the CompanyId for contact on the basis of Company name present. Save the address with respect to Company and sync the existing data.

**Comment by prashantaggarwal1999** [comment]
Create the stored procedure to fetch the company details and bind on the newly created partial view.
