### ISSUE TITLE
Discussion -  User should be able to view only the PPP he is assigned to and rest should not be visible.

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#2]
The approach was suggested by Akhil under contact bridge table discussion and this was deferred.

Review this in next meeting

**Comment by bharathrl** [comment]
[May 31st, 2019 discussion.docx](https://github.com/meridianww/M4PLBase/files/3251628/May.31st.2019.discussion.docx)

Discussed on May 31st and Minutes of the meeting was prepared and shared with the client for preview.

**Comment by bharathrl** [comment]
All the mentioned points looks fine, but Nathan will review it once again and confirm.
