### ISSUE TITLE
When assigning roles for a user in Program/Project/Phase-> contacts, roles will be fetched from ref roles

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#20]
As a user of the application, I should be able to assign a role to a user under a program - >contact tab.

Business rules,

1. Admin will navigate to Program/Project/Phase -> Contacts -> New/Edit -> pop up-> Org role code (DropDown) to assign a role to a user.

2. Admin will enter data in other fields.

3. The org role code values will come from ref roles (The roles belong to a customer, vendor, and Organisation). 
Case -1 If organisation role is selected in org role code drop down, then the contact which belong to organisation will only be displayed
Case -2 If Customer role is selected in org role code drop down, then the contact which belong to selected Customer will only be displayed
Example - If AWC is the customer then only AWC contacts will be displayed
Case -3 If Vendor role is selected in org role code drop down, then the contact which belong to mapped vendor will only be displayed
Example - If we have 5 Vendors in vendors module and 2 vendors are mapped, then the contacts which are assigned to 2 mapped vendors will be displayed.

4. Based on the org role code assigned to a contact the security permission will be assigned to the user.

Acceptance Criteria:
1. On click of Save - 
      i. Check if all the mandatory fields are filled.
     ii. Org role code will be assigned to the contact selected in the contact drop down and security permission will be assigned based on the security defined for that role in ref roles.

2. On click of Close-
   Display a confirmation message “You have unsaved data. Do you want to save changes and proceed? “
Save - On click of save button, save the data and navigate to Program ->Contact tab  
Don’t Save - On click of Don’t Save button, don’t save the data but navigate to Program ->Contact tab   
Cancel - On click of cancel button, remain on the same page.

Definition of Done
1. All mandatory fields should be filled and saved.
2. Should pass regression test and unit testing.
3. Pass testing as per acceptance criteria.

**Comment by ChauhanNikhil** [comment]
Create Sp to fetch details of role passed and updated existing sp to filter data based on ref role
