### ISSUE TITLE
Display of deleted contact or type

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#22]
1. If a contact assigned to a program/project/phase/job/DC location and later if the contact is deleted, then show the value in drop down as <name> (deleted)

2. If contact is assigned as type- driver and the type is deleted/inactive/archived then show <Type><deleted/inactive/archived>

**Comment by prashantaggarwal1999** [comment]
- Investigate the implementation to show the deleted contacts in the dropdown.
- Code changes to pass the StatusId as Column while getting the Contact Combo Box result and write code to add the Inactive and Delete text on the server-side
- The stored procedure changes to fetch all the contacts even if it deleted or Inactive in the system.
- Code changes to make the Row inactive to select for the contacts which are InActive/Deleted
