### ISSUE TITLE
Assign location and rates to program ->Price codes and cost codes.

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#27]
As a user of the application, I should be able to assign location and rates to program ->Price codes and cost codes.

Business rules,

1. Program -> Price codes tab will have default values defined by the user but the values will not be to any specific location
2. Program -> Cost codes tab will have default values defined by the user but the values will not be to any specific location

3. Program -> Price codes tab, on right-click, add an option "Retrieve location". clicking on this pop up will appear wherein the left side the assigned vendor location will be displayed and based on the user selection those selected values will appear in the right side of the pop-up. 
Add Assign and unassign buttons

4. Program -> Cost codes tab, on right-click, add an option "Retrieve location". clicking on this pop up will appear wherein the left side the assigned vendor location will be displayed and based on the user selection those selected values will appear in the right side of the pop-up. 
Add Assign and unassign buttons.

Acceptance Criteria:

Point 1 and Point 2
Price and cost codes will have default rates which will always appear in the first row, this value can be updated by the user.

Point 3 & Point 4
clicking Assign -> Should assign the location to price/cost codes (Add master-detail grid for the number of location. 
clicking Unassign-> Should unassign the location to price/cost codes (Add master-detail grid for the number of location. 

Definition of Done
1. All mandatory fields should be filled and saved.
2. Should pass regression test and unit testing.
3. Pass testing as per acceptance criteria and Business rules

Note - 

1. Context menu option name "Retrieve location" might change later

**Comment by kirtya** [comment]
Client side changes to bind the Assigned and Unassigned Tree View List and write the methods to call the controller method on the click of Assigned/Unassigned. Create the method in Controller to Handle server side request for Assign/Unassigned

**Comment by kirtya** [comment]
Code modification in Data Access Project to Save the Selected locations in the database for Price and Cost.

**Comment by kirtya** [comment]
Database object modifications to save and get the selected locations for Cost Code

**Comment by kirtya** [comment]
Update the code in Business Layer and Entity project to update the Model and logic which is required to Save and Get Cost Code.

**Comment by kirtya** [comment]
Updated stored procedure dbo.InsProgram to make a default location for Price and Cost Code while creating a new program

**Comment by kirtya** [comment]
Code changes to show the required columns in Parent Grid with proper mapping

**Comment by kirtya** [comment]
Code changes and Removing the Edit and New Actions For Parent Grid In Cost code and make required changes to make available actions workable

**Comment by kirtya** [comment]
Update SPs of InsPrgBillableRate with ProgramId to return the associated program ID

**Comment by kirtya** [comment]
Updated the Program Price Code properties in Column Alias table and created script as well

**Comment by kirtya** [comment]
Code implementation for Data layer and business layer to get the value as respective to selected program id and send to front end devexpress grid to show

**Comment by kirtya** [comment]
Call respective SPs in code behind as per requested Price Code to get the detail and show in devexxpress grid

**Comment by kirtya** [comment]
Update the SPs of program billable rate to show the data in child grid as per selected price code

**Comment by kirtya** [comment]
Create SPs to get all assigned vendor location to show in grid

**Comment by kirtya** [comment]
Added contact type in refoption table and added enum in code level for Assign Vendor and added logic to filter only required option for price code grid right click

**Comment by kirtya** [comment]
Customize onCallBack rout of Map Vendor form view close option and added condition in DevExpress JS script to reload the grid as well

**Comment by kirtya** [comment]
Customize the grid setting for price code child grid view data to distinguish the grid name, as one name can be populate at a time

**Comment by kirtya** [comment]
Customize the choose column URL setting at the time of price code child grid setting creation

**Comment by kirtya** [comment]
Customize the price code child grid setting for saving record call back url.

**Comment by kirtya** [comment]
Find the root cause of Choose Column Save and Fix

**Comment by kirtya** [comment]
Update the Stored Procedure to get only the active Billing Locations

**Comment by ChauhanNikhil** [comment]
made DB changes an set up environment for the Map Location for the programs
made entries to column aliases and  tab tables
