### ISSUE TITLE
Copy program price/cost codes to jobs price/cost codes if the entered vendor location code matches

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#29]
As a user of the application, I should be able to copy program price/cost codes to jobs price/cost codes if the entered vendor location code is matched

Business rules,

1. In the Jobs (Program), based on the vendor location code in job details,

Case -1 If job vendor location code matches the Program -> Vendor->Location code, the cost data will be copied from Program -> cost codes -> Location code to Jobs (Program) -> cost codes
Case -2 If job vendor location code is not matched in the program ->  Vendor->Location code, the default values in the program -> cost codes will be copied to the location of Jobs (Program) -> cost codes

2. In the Jobs (Program), based on the vendor location code in job details,

Case -1 If job vendor location code matches the Program -> Vendor->Location code, the price data will be copied from Program -> price codes -> Location code to Jobs (Program) -> price  codes
Case -2 If job vendor location code is not matched in the Program -> Vendor->Location code, the default values in the program -> price codes will be copied to the location of Jobs (Program) -> price codes

3. Jobs -> Driver
 
Based on the location entered in Vendor location code, the respective vendor's driver contact will be displayed in the dropdown, if vendor location code is not matched then no contact will be displayed in the contact drop-down

Acceptance Criteria:

Point 1 & 2

Vendor location code will be autocomplete field, based on the location code entered in the Job details

Case - 1 If found, copy the Program->price codes to job (Program)-> price code tab 
Case - 2 If found, copy the Program->cost  codes to job (Program) -> cost code tab
Case - 3 If not found, copy the default values from Program->price codes to job (Program) -> price code tab 
Case - 4  If not found, copy the default values from Program->cost codes to job (Program) -> cost code tab 

Note-  
1. Whichever is found either price/cost codes, copy those values, otherwise copy the default values.
2. Mapping sheet attached, still, some of the mappings of the fields are in the discussion (Highlighted in yellow color)
3. Program Price/Cost Records - Billable Price Field is Read-Only (Retrieved from NAV)
4. Job Price/Cost Records - All Fields Read-Only Except for Quantity
5. If NAV is updated and Program is re-synced to NAV Price List
      Existing Jobs keep previous Price/Cost values
       New Jobs use updated Program Price/Cost values

Definition of Done
1. All mandatory fields should be filled and saved.
2. Should pass regression test and unit testing.
3. Pass testing as per acceptance criteria and Business rules

**Comment by ChauhanNikhil** [comment]
Cost price and billable price has been copied on creation on new job , 
Functionality covered --1. If there is no matched vendor location then default rate will get copied to respective cost and price tab.
2.Id a user updated vendor code for the job then based on vendor Location  cost and price will be updated in Price and cost tab.
3.New autocomplete tokenbox  has been provided  for the assigned vendors.
