### ISSUE TITLE
Return Order - Schedule Pick Up Needs to Have Editable Date Field

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#295]
The Schedule Pick Up action should be similar to the Schedule Initial Appointment action with the Scheduled date field being editable for the user to specify the Scheduled Pick Up Date.

**Comment by nmfujimoto** [comment]
![image](https://user-images.githubusercontent.com/50392020/93249251-de251e00-f745-11ea-9a67-98ed4072ac27.png)

Notice on the Schedule Initial Appointment action the date is editable:
![image](https://user-images.githubusercontent.com/50392020/93249344-014fcd80-f746-11ea-8d7e-a3d3a222c0ac.png)

**Comment by nmfujimoto** [comment]
Need to add the "Pick Up Date" control to the Schedule Pick Up action. The date field will update the Arrival Date Planned field in the Job.

**Comment by prashantaggarwal1999** [comment]
@nmfujimoto this change is ready on the Development environment, please have a look over there. Changes will deploy on production on Wednesday. @KamalAdhikary @kirtya

**Comment by nmfujimoto** [comment]
Might need to create a separate task. 

Need to create all the AWC Reschedule actions that we currently have for Original order type and create Program Reschedule records for the Return order type Reschedule actions. The Original and Return Reschedule actions are the same but the Job Tracking filters on Order Type so for a Return job the Program Reschedule actions are for Original order types so the user cannot see them for Returns.

![image](https://user-images.githubusercontent.com/50392020/94497827-4398f600-01ad-11eb-9537-674101ab8ae2.png)

**Comment by nmfujimoto** [comment]
Can use the same for for Return order Reschedule actions. Update the title to say Reschedule

![image](https://user-images.githubusercontent.com/50392020/94497945-9c688e80-01ad-11eb-8bec-d25e126a6f1e.png)

**Comment by nmfujimoto** [comment]
Please add the Reschedule actions for Return orders to all AWC program(s) and projects.

**Comment by nmfujimoto** [comment]
Reschedule actions for Return orders should update the Arrival Date Planned field. Need to change the wording on the Reschedule dialog form to say Arrival Date Planned for Return order Reschedule actions.

![image](https://user-images.githubusercontent.com/50392020/95516946-ee12d500-0974-11eb-8955-3d5cb7ae1079.png)
