### ISSUE TITLE
Saving Changes to Job Changes Tracking Records

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#296]
When saving changes to a Job, when the page refreshes after saving the records displayed in the Tracking tab are different. If the user refreshed the browser page then the original tracking records are displayed again.

**Comment by nmfujimoto** [comment]
Job Form before clicking on Update/Save:
![image](https://user-images.githubusercontent.com/50392020/93270474-189eb300-f766-11ea-9cd5-b90cb6dfe73e.png)

Job Form after the Update (where are these Tracking records pulling from?):
![image](https://user-images.githubusercontent.com/50392020/93270494-20f6ee00-f766-11ea-884a-346b0cadbc48.png)

**Comment by KamalAdhikary** [comment]
@nmfujimoto This issue is fixed in staging server. Please have look into it.

**Comment by nmfujimoto** [comment]
@KamalAdhikary resolved this issue and the change is in staging.
