### ISSUE TITLE
Discuss Modifying Delivery Date Planned Field

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#297]
Operations is getting confused by the Delivery Date Planned being updated by the actions.

**Comment by nmfujimoto** [comment]
Need to understand what possible consequences and changes would be encountered if we leave the Delivery Date Planned field blank/null until the user adds a Schedule/Reschedule action or an xCBL Schedule change is received. The EDI processor will only map the Estimate Delivery Date we receive from our customer to the Delivery Date Baseline field. The previously mentioned actions will populate the Delivery Date Planned field. No changes required for the actions.

Update the label of the JobDeliveryDatePlanned field to "Scheduled Delivery Date" in the Job Form and Grid.

What changes would be required in the Job Dashboard and Report queries?

**Comment by nmfujimoto** [comment]
![image](https://user-images.githubusercontent.com/50392020/93289362-1010a180-f793-11ea-9fef-6ed5f715b281.png)

**Comment by nmfujimoto** [comment]
In Job Report Date Reference drop-down:
Schedule Date will compare to JobDeliveryDateTimePlanned (Alias is Scheduled Delivery Date, see previous comment) 
Delivery Date will be renamed to Delivered Date and will compare to JobDeliveryDateTimeActual. It will be used to search for jobs that are already delivered.

**Comment by nmfujimoto** [comment]
Remember, the JobDeliveryDateTimePlanned (Scheduled Delivery Date) field will be null/blank for any new jobs. The field will be populated when a user/xCBL adds the Schedule Initial Appt. or Reschedule actions.

**Comment by prashantaggarwal1999** [comment]
@nmfujimoto Changes are done for the same and will be deployed on the Dev Environment today, request you to go ahead and check once from your end. @KamalAdhikary @kirtya
