### ISSUE TITLE
Multi-Select Behavior for Jobs (Grid, Dashboard)

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#309]
Can we modify the behavior so that the background check on common Actions available for the selected jobs is performed when the user right-clicks and wants to choose an action? Currently, the Loading... spinner is displayed after each job is selected and takes a second while checking so the user cannot quickly select the jobs. 

Can a Select All checkbox option be added?

**Comment by nmfujimoto** [comment]
Looking at adding Tracking buttons to ribbon so jobs can be selected quickly. Researching solution, looking at adding to Dashboard Detail grids first, then Job grid.

**Comment by kirtya** [comment]
@nmfujimoto 
Functionality has been completed, to add action and gateway from ribbon menu, for multi selection of jobs from job dataview.
We will give a demo to you in our up coming review meeting.
Pending: 
1. Design of popup form view for selection of action and gateway to be add, for respective jobs
2. Code clean up for existing functionality to add context menu for job grid

**Comment by nmfujimoto** [comment]
Why is the Loading... pop-up still displaying?

![image](https://user-images.githubusercontent.com/50392020/96320421-2fcffb00-0fc7-11eb-9fe6-ef08bbfa5b16.png)

**Comment by nmfujimoto** [comment]
The Schedule/Reschedule actions should be filtered by Order Type, e.g.  Original order would display Schedule Initial Appt. and Return order would display Scheduled Pick Up.

![image](https://user-images.githubusercontent.com/50392020/96397967-8aac5280-117f-11eb-93e9-602bf4964ae2.png)

**Comment by kirtya** [comment]
Feature has been developed and testing is in progress.

**Comment by Madhusmi** [comment]
In the job advance report  the add action and add gateway implementation in the ribbon are not working as expected  but  meanwhile In "Job card" it is working.So kindly suggest about this

**Comment by nmfujimoto** [comment]
The Job Dashboard is not working for Multi-Select Actions. 

I selected 3 jobs and tried to add the Schedule Initial Appt. action but the system is stuck on the loading message.

![image](https://user-images.githubusercontent.com/50392020/96619462-137bd900-12bb-11eb-9edf-876723d81dd3.png)

**Comment by KamalAdhikary** [comment]
@nmfujimoto  issue is resolved and verified in Production and staging server.

**Comment by Madhusmi** [comment]
@nmfujimoto Testing is completed from QA end and it is working as expected.

**Comment by nmfujimoto** [comment]
This is not working in Production. The dashboard is not refreshing with the new date value.

I selected 2 orders to add the Schedule Initial Appt. action. Original Date is 9/4/2020
![image](https://user-images.githubusercontent.com/50392020/97039600-89817980-1521-11eb-9cb4-ad6c5472da18.png)

After adding the action the Scheduled Delivery Date value is still the old value.
![image](https://user-images.githubusercontent.com/50392020/97039652-9d2ce000-1521-11eb-88c7-7d4c85953b07.png)

Navigating to one of the jobs, the Schedule Initial Appt. action is present and the updated Schedule Delivery Date is the new value.
![image](https://user-images.githubusercontent.com/50392020/97039728-b766be00-1521-11eb-925b-fffdd6323dc7.png)

**Comment by KamalAdhikary** [comment]
@nmfujimoto 

Issue has been resolved in production and tested for DO-QA customer. Please review once from your end.
