### ISSUE TITLE
OSD Report To Display Overage, Short and Damaged Items

### ISSUE THREAD

**Issue by meridian-dev** [meridianww/M4PLBase#315]
Need to add to the Job Report module the ability to generate a report for OSD issues.

**Comment by meridian-dev** [comment]
The OSD Report should be available in the Job Report Type drop-down:
![image](https://user-images.githubusercontent.com/71733486/94208626-1f70a880-fe7f-11ea-9f05-fee908946dec.png)

Search options should include:

- Customer
- Program
- Origin
- Destination
- Brand
- Product Type
- Order Type
- Job Status
- Date Reference
- Start/End Dates
- Search

**Comment by kirtya** [comment]
Feature has been developed and testing is in progress.

**Comment by nmfujimoto** [comment]
@nsmith00785 Can you provide a sample of a current OSD report?

**Comment by nmfujimoto** [comment]
Example of what AWC uses:
![image](https://user-images.githubusercontent.com/50392020/97238635-17ba6180-17a7-11eb-9ff0-241451f5f453.png)

**Comment by bharathrl** [comment]
@nmfujimoto Can you please review the mappings and confirm

SCAC - Meridian/Organisation Name
DC - Vendor DC location/Site Code
Manifest - Manifest No
Exception Type - Job module-> Tracking Tab->Exception added
O/S/D control ID - Job module-> Cargo Tab-> Summary-> ID 
Product Information - Job module-> Cargo Tab-> Summary-> Part code
Image count - Job module->Document->Image count only
Auditcount - 

CC - @prashantjustp

**Comment by nmfujimoto** [comment]
@bharathrl @prashantjustp 

DC: Site Code
Manifest: Manifest Number
Exception Type: Exception Added (Status Code)
> D - Damaged
> S - Short
> O - Overage

Order Number: Order Number
Serial Number: Cargo Serial Number
Part Code: Cargo Part Code

**Comment by Madhusmi** [comment]
@nmfujimoto Testing is completed from QA end and it is working as expected.
