### ISSUE TITLE
DigiCert SSL Expiration 10/7/2020

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#319]
Need to renew the wildcard SSL certificate for *.meridianww.com

**Comment by nmfujimoto** [comment]
Here's the link to renew a certificate:
https://docs.digicert.com/manage-certificates/renew-ssltls-certificate/

We first need to generate the CSR if we don't have one:
https://www.digicert.com/kb/csr-creation.htm

**Comment by nmfujimoto** [comment]
DEV:
m4pl-dev.meridanww.com
b2b.meridianww.com

PROD:
m4pl.meridianww.com
m4pl-api.meridian.com
bizmobl-api.meridian.com
electrolux-api.meridian.com
awc-api.meridian.com

**Comment by prashantaggarwal1999** [comment]
![image](https://user-images.githubusercontent.com/53289874/95088593-c4716800-0740-11eb-9a93-2ef7a8f7c2f4.png)

**Comment by nmfujimoto** [comment]
@prashantaggarwal1999 The certificate has been issued by Digicert.

![image](https://user-images.githubusercontent.com/50392020/95140121-f4aa0e00-0722-11eb-98d9-57b292e11215.png)

**Comment by nmfujimoto** [comment]
@prashantaggarwal1999 Installed on Production APP and Dev App.

**Comment by prashantaggarwal1999** [comment]
@nmfujimoto Certificate is installed on all the mentioned servers.
