### ISSUE TITLE
Driver Scrub Not Pulling Correctly Production Server

### ISSUE THREAD

**Issue by nsmith00785** [meridianww/M4PLBase#321]
I tried to add the driver scrub from 9/20-9/26 and then when i tried to extract out of M4, it just pulls the scrub from 9/13-9/19.

**Comment by nmfujimoto** [comment]
@nsmith00785 imported the raw data for the Driver Scrub report for the week of 9/20/2020 - 9/26/2020 into M4PL. 

@nsmith00785 - What would be the expected results? 

Choosing Driver Scrub report and setting the Start and End dates to 9/20/2020 - 9/26/2020 displays the following records:
Total of 822 orders
![image](https://user-images.githubusercontent.com/50392020/94850371-b4bdf080-03db-11eb-961b-af3606b0adae.png)

Changing the Start and End dates to 9/13/2020 - 9/19/2020
Total of 440 order
![image](https://user-images.githubusercontent.com/50392020/94850542-eafb7000-03db-11eb-8b94-994380699567.png)

**Comment by prashantaggarwal1999** [comment]
@nmfujimoto There are a couple of jobs where we have the same JobCustomerSalesOrder, check the Query Select * From JOBDL000Master Where Id IN (96121,97879). In this case, the Driver Scrub Report is showing duplicate record. Please let us know if this is the correct Behaviour.

**Comment by nmfujimoto** [comment]
Adding ShipDate to auto-populated and will filter on that date.

**Comment by nmfujimoto** [comment]
@nsmith00785 Can you please test this in the development system. We have data for 9/13-9/19 and 9/20-9/26. You can import more of the raw data if you have the files. 

- Select the customer (AWC)
- If you want to import, click on the button else select the Start and End dates to generate the report
