### ISSUE TITLE
Add Remittance Report to Ribbon

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#322]
Need to add a button to the Reports section to allow vendors to retrieve remittance data. The user should be able to enter a Check Number and retrieve all the posted purchase invoices that the Check Number applied to.

**Comment by nmfujimoto** [comment]
Process:
1.	User clicks on button and enters Check Number “80007”
2.	Call NAV web service Vendor Ledger Entries – Filter on Document_No “80007”
a.	https://nav.meridianww.com:7048/Dev/ODataV4/Company('Meridian')/Vendor_ledger_Entries?$filter=Document_No%20eq%20%2780007%27
b.	Retrieve Entry_No field value “1320”
c.	The record returned is Document_Type “Payment”
3.	Call NAV web service Vendor Ledger Entries again with a different filter – Filter on Closed_by_Entry_No “1320”
a.	https://nav.meridianww.com:7048/Dev/ODataV4/Company('Meridian')/Vendor_ledger_Entries?$filter=Closed_by_Entry_No%20eq%201320
b.	Retrieve all Posted Invoices
c.	The records returned are Document_Type “Invoice”
4.	Retrieve additional information for each Posted Purchase Invoice record – Example filter on ‘PI0000000139’ 
a.	https://nav.meridianww.com:7048/DEV/ODataV4/Company('Meridian')/PostedPurchaseInvoice?$filter=No%20eq%20%27PI000000139%27
5.	CSV Report fields
a.	No. – Posted Purchase Invoice No. field
b.	M4PL Job ID – Posted Purchase Invoice Vendor_Invoice_No. field
c.	Order Number – Posted Purchase Invoice Vendor_Order_No. field
d.	Document Date – Posted Purchase Invoice Document_Date field
e.	Amount – Vendor Ledger Entries Amount (Match on Vendor Ledger Entries Document No. == Posted Purchase Invoice No.)

**Comment by nmfujimoto** [comment]
@prashantaggarwal1999 I would like us to look into adding a layer of security into the Remittance function. In the Vendor Ledger Entries there is the Vendor_No. field (e.g. TSP vendor is V-80000) so the Remittance should be restricted to employees or users assigned to TSP vendor. Another vendor should not be able to type in Check No. 80007 and download the remittance data for TSP. 

![image](https://user-images.githubusercontent.com/50392020/95514903-9d4dad00-0971-11eb-84ff-8fb7246b5ef1.png)

**Comment by prashantaggarwal1999** [comment]
@nmfujimoto changes are done you can view the changes on dev environment, please do Cltl+F5 once if changes will not reflect. The error message also now showing on the same page.

![image](https://user-images.githubusercontent.com/53289874/95576712-8b8e0780-0a4e-11eb-9e14-4efc8af885b8.png)

**Comment by nmfujimoto** [comment]
@prashantaggarwal1999 Security implemented and pushed to Dev server.

**Comment by nmfujimoto** [comment]
@kirtya Updated remittance to display in single page.

**Comment by nmfujimoto** [comment]
In Dev server, a new tab is opened but nothing is produced.

**Comment by nmfujimoto** [comment]
Script was updated so need to hit Ctrl + F5 to update script.

**Comment by nmfujimoto** [comment]
@kirtya Can we please remove the prompt to save after retrieving the data? Why is the pop-up dialog asking to save?

**Comment by kirtya** [comment]
Feature has been developed and testing is in progress.
