### ISSUE TITLE
DEV - Accessorial Charges Should Not Be Added By Default

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#328]
The Accessorial charges for AWC should be added by the user in the same manner as Electrolux charges can be added by right-clicking and choosing to add a charge from the context menu.

**Comment by nmfujimoto** [comment]
Development Server
![image](https://user-images.githubusercontent.com/50392020/94953165-ebf3d680-049b-11eb-90c8-fbe2b8144ca7.png)

**Comment by prashantaggarwal1999** [comment]
@nmfujimoto here changes has been made, now the application will copy only the default charge from the default rate if location code is not present otherwise it will not copy any charge.
