### ISSUE TITLE
DEV - Cannot Create SO/PO in NAV

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#329]
Need a better error message as this problem with creating SO/PO in NAV is too common.

**Comment by nmfujimoto** [comment]
Why is the SO/PO failing to be created in NAV? I thought this was fixed.

![image](https://user-images.githubusercontent.com/50392020/94953295-2a899100-049c-11eb-84e0-b5d48b708c53.png)

**Comment by prashantaggarwal1999** [comment]
@nmfujimoto changes have been made to fix the issue, please try and let us know if you are still facing the issue.

**Comment by nmfujimoto** [comment]
@prashantaggarwal1999 I am testing using the same order that I originally tried (RP 31988330) and I get the same message stating the order could not be created in NAV.

![image](https://user-images.githubusercontent.com/50392020/95114232-7cc6ee00-06f8-11eb-88e4-2277fa2c9338.png)

**Comment by radha4116** [comment]
Issue has been fixed in development server.
