### ISSUE TITLE
Update Action Forms With Correct Label

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#334]
The Action Forms for Schedule or Reschedule should display Scheduled Delivery Date instead of Delivery Date Planned.

**Comment by nmfujimoto** [comment]
The Action forms should be consistent with the Job Form

![image](https://user-images.githubusercontent.com/50392020/95278756-c2bda800-0805-11eb-8983-078b181a320a.png)

![image](https://user-images.githubusercontent.com/50392020/95278759-c6512f00-0805-11eb-9fbf-9a0bbd07f4be.png)

**Comment by bharathrl** [comment]
@nmfujimoto 

We will rename "Schedule delivery" to "Schedule delivery date" in the following places -
1. Schedule - Initial Appointment
2. Canceled  - Customer Canceled Order

CC - @KamalAdhikary

**Comment by nmfujimoto** [comment]
Yes, but make the wording capitalized, “Schedule Delivery Date”.

Thank you,

Nathan Fujimoto
nfujimoto@meridianww.com<mailto:nfujimoto@meridianww.com>
Business: (951) 268-2190
Cell: (951) 616-9271

[fm_meridian_branding_logo_filled_small_v1]
