### ISSUE TITLE
Tracking Records ACD Values

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#335]
Not all of the Tracking records are displaying the ACD value correctly.

**Comment by nmfujimoto** [comment]
In the image below, the Schedule, On Hand and Outbound records were created around 5:04PM PDT. Why are two of the records displaying in UTC time?

![image](https://user-images.githubusercontent.com/50392020/95278898-1d570400-0806-11eb-8f10-e562d9216e00.png)

**Comment by bharathrl** [comment]
@nmfujimoto Can you please provide the JobID for this

CC - @radha4116

**Comment by nmfujimoto** [comment]
@bharathrl @radha4116 You can use Job ID 211075. I just tried this in Production and added the Schedule Initial Appt. action at 8:36 PM PDT, and the On Hand and Outbound gateways at 8:37 PM PDT. You can see the 2 new gateways are displaying the ACD in UTC time.

![image](https://user-images.githubusercontent.com/50392020/95284817-05867c80-0814-11eb-8d3b-9a385fc222bb.png)

**Comment by prashantjustp** [comment]
Code fix is done, Testing is pending...

**Comment by prashantaggarwal1999** [comment]
@prashantjustp Logic for ACD value should be as follows: 

1. If Job has a valid destination present then ACD will be the current DateTime on the destination TimeZone. For Example, if job Destination is Schaumburg then Timezone will be CST and ACD value will be the current date and time on the Central Time Zone.
2. If Destination timezone is unknown then ACD value will be the current pacific date and time. 

Please test your changes with this logic. @nmfujimoto please correct me if I am wrong here.
