### ISSUE TITLE
EDI Mapping Record Throwing Error

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#338]
When a user tries to choose an EDI field name in the EDI Mapping under the Program module an error dialog is displayed.

**Comment by nmfujimoto** [comment]
![image](https://user-images.githubusercontent.com/50392020/95537607-99864e80-09a2-11eb-9845-15787268069d.png)

**Comment by nmfujimoto** [comment]
Please make sure the columns are wide enough to display the names:

![image](https://user-images.githubusercontent.com/50392020/95537920-b3c02c80-09a2-11eb-9875-2fdcac58b7c0.png)

**Comment by kirtya** [comment]
Feature has been developed and testing is in progress.
