### ISSUE TITLE
Manually Adding Gateways Are Not Inheriting From Program Default Values

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#340]
When a user adds a gateway to a job the default values such as Completed or Date Reference are not inheriting from the Program Default Gateway records. This is causing an issue as it requires the user to manually check the Completed checkbox when adding the gateway. If the user does not remember to check the Completed box then the next gateway is not available.

**Comment by nmfujimoto** [comment]
@prashantaggarwal1999 I see the gateways are inheriting the Completed value, but they are still not inheriting the Date Reference. This is not a major issue as we are not using the Date Reference values anymore but it's more for consistency at this time.

**Comment by kirtya** [comment]
Feature has been developed and testing is in progress.
