### ISSUE TITLE
DEV - Dashboard Not Displaying Data When Filtering on AWC

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#341]
When a user (kvaugh) logs in and filters on AWC the Dashboard not records are displayed.

**Comment by nmfujimoto** [comment]
Production is not showing this issue.

![image](https://user-images.githubusercontent.com/50392020/95636297-a7d87700-0a43-11eb-8a8a-09e8f74c041a.png)

**Comment by nmfujimoto** [comment]
@KamalAdhikary Please look into this issue.

**Comment by radha4116** [comment]
@nmfujimoto verified this issue on development server please check and close this issue

**Comment by kirtya** [comment]
Feature has been developed and testing is in progress.
