### ISSUE TITLE
DEV - Adding OSD Exception Does Not Update Quantity

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#342]
When adding an Exception to an AWC order the OSD values for the Cargo record are not updated.

**Comment by nmfujimoto** [comment]
Job ID: 192672
Added a Damaged Exception for the Cargo Id 6366070, with the damaged quantity being 1. In the Job Cargo records the CgoQtyDamaged is not populated with the quantity from the Exception.

![image](https://user-images.githubusercontent.com/50392020/95771767-785a8200-0c70-11eb-9731-48ff8b7f213d.png)

**Comment by nmfujimoto** [comment]
This issue is also seen in Production too.

**Comment by kirtya** [comment]
Feature has been developed and testing is in progress.
