### ISSUE TITLE
xCBL - 48 Hour Change, Why Display On Dashboard?

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#343]
Why are orders displayed for xCBL 48 Hour change when the date is greater than 48 hours?

**Comment by nmfujimoto** [comment]
![image](https://user-images.githubusercontent.com/50392020/95796861-d0aa7780-0ca2-11eb-883d-e89c2d5b3a0e.png)

**Comment by nmfujimoto** [comment]
![image](https://user-images.githubusercontent.com/50392020/95796943-064f6080-0ca3-11eb-8264-5a1c8eef48e9.png)

**Comment by nmfujimoto** [comment]
![image](https://user-images.githubusercontent.com/50392020/95812373-175f9800-0cca-11eb-901a-c78e7996b7d2.png)

**Comment by kirtya** [comment]
Feature has been developed and testing is in progress.

**Comment by Madhusmi** [comment]
@nmfujimoto Testing completed on QA and Staging Server and it is working as expected.
