### ISSUE TITLE
xCBL Actions Column Name - Use Alias

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#350]
The xCBL pop-up dialog to accept/reject changes needs to use the Alias name of the field.

**Comment by nmfujimoto** [comment]
This has been asked repeatedly during our meeting to correct and the issue is still present. Please change the alias name of the fields.

![image](https://user-images.githubusercontent.com/50392020/96766960-b9e5de00-1390-11eb-9e50-f3334b51eb7f.png)

**Comment by prashantjustp** [comment]
@nmfujimoto, @bharathrl 
Code changes are checked in, Testing is pending.

**Comment by Madhusmi** [comment]
@nmfujimoto Tested in QA server and it working as expected.
