### ISSUE TITLE
M4PL API - InsertJobGateway

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#355]
Error Logs are showing the API call is not available on occasions. We need to find why the call fails randomly.

**Comment by nmfujimoto** [comment]
The error for the API call is: 
The remote server returned an error: (401) Unauthorized.

This occurred at 2:21AM Pacific time. Was there any work performed on the Production server at that time?

**Comment by nmfujimoto** [comment]
The same error occurred at 5:25AM Pacific for the InsertJobGateway and AddDriver API calls.
The remote server returned an error: (401) Unauthorized.

**Comment by KamalAdhikary** [comment]
@nmfujimoto 

API has been verified/tested for production & staging server and it is working as per expectation/requirement. Please review and let us know if  facing any issue.

**Comment by nmfujimoto** [comment]
public static string GetAuthToken()
        {
            return DateTime.UtcNow > ExpirationTime ? GenerateToken() : Token;
        }

The Token does not seem to be valid even when the expiration time is still valid.

**Comment by prashantaggarwal1999** [comment]
@nmfujimoto Please replace the GetAuthToken method with the below code and let us know if you are still facing the issue:

public static string GetAuthToken()
		{
			if (string.IsNullOrEmpty(Token) || ExpirationTime.Equals(DateTime.MinValue) || DateTime.UtcNow > ExpirationTime.AddHours(-1))
			{
				Token = string.Empty;
				Token = GenerateToken();
			}

			return Token;
		}

**Comment by nmfujimoto** [comment]
@nmfujimoto Please comment so we can close.

**Comment by nmfujimoto** [comment]
@Madhusmi Verified that updated code is working for token authorization.
