### ISSUE TITLE
Dashboard - POD Completion Not Correct

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#358]
The No POD Completion card on the dashboard does not match the number of orders that currently are missing a POD.

**Comment by nmfujimoto** [comment]
Filtering on Electrolux, the dashboard card shows a total of 18 orders that are missing PODs.
![image](https://user-images.githubusercontent.com/50392020/97502737-f8e7d680-1930-11eb-85a3-b179b6004fd7.png)

Clicking on the No POD Completion card to drill down to the details shows a total of 19 orders.
![image](https://user-images.githubusercontent.com/50392020/97502768-0ac97980-1931-11eb-937f-0efda14cb277.png)

Viewing Electrolux orders in the Job Grid and filtering on Active status and Delivered gateway status show a total of 39 orders. 
Order number 7803680816 is not displayed on the dashboard for No POD, but does have a Document attachment. Why is this order not listed on the dashboard?
![image](https://user-images.githubusercontent.com/50392020/97503101-a0fd9f80-1931-11eb-8da5-207179f5089e.png)

**Comment by kirtya** [comment]
Issue has been resolved and tested as per above mentioned steps in **staging & production server**, please review once and let us know if still issue is there.

**Comment by Madhusmi** [comment]
@nmfujimoto Testing completed in both Staging and Production server and it working as expected.
