### ISSUE TITLE
VOC Surveys - Need To Verify Process Is Working

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#361]
All requests over the last 30 days do not include a Contract Number when viewing the survey answers. If you use an EntityTypeId from an existing record that is null for Contract Number the correct Contract Number is retrieved.

Is this an issue with Shipping Controller (PBS Mobile) or our web service?

**Comment by nmfujimoto** [comment]
EntityTypeId: 2040605OC - The survey records in the image show that on 11/2/2020 the survey was retrieved but no Contract Number is populated. Using the same EntityTypeId on 11/3/2020 in the URL retrieves the correct Contract Number.

![image](https://user-images.githubusercontent.com/50392020/97948491-97b36f00-1d45-11eb-96a3-ad5d8c4b33d1.png)

**Comment by KamalAdhikary** [comment]
@nmfujimoto we found the issue with PBS service. we will discussed tomorrow meeting.
