### ISSUE TITLE
Do Not Populate The Start And End Dates Fields In The Job Report Screen

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#366]
All Report types should not have the Start and End dates populated when selecting a report type. If the Start and End date are populated by the user do not overwrite the values if the user selects a different report.

**Comment by nmfujimoto** [comment]
![image](https://user-images.githubusercontent.com/50392020/98306292-6078d400-1f78-11eb-8242-bd5326746d82.png)

**Comment by Madhusmi** [comment]
@nmfujimoto Testing completed from QA end and it is working as expected.
