### ISSUE TITLE
Capacity Report - Not Showing Data

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#370]
I imported the capacity report for AWC 2019 but no data was displayed after selecting 2019 year and hitting the Generate Report button.

**Comment by nmfujimoto** [comment]
Please look into calculations for FP% and ESFU.

We should be using currently "On Hand" orders and comparing against capacity values for each location. This allows us to use historical capacity (e.g. 2018, 2019) with our current on hand orders.

At this time Andrews SC should have multiple orders that are On Hand, and this will change on a daily basis. The user should be able to run the report each day and see how much capacity the current cargo in the warehouse is is taking up.

**Comment by Madhusmi** [comment]
@nmfujimoto Testing completed from QA end and it is working as expected.

**Comment by nmfujimoto** [comment]
Need to use the Customer Program/Project Location Codes with the Like condition to match orders on.

Example:
![image](https://user-images.githubusercontent.com/50392020/99929416-0317ad80-2d02-11eb-8e6b-c0d9516920e0.png)

**Comment by Madhusmi** [comment]
@nmfujimoto Testing completed in QA and Staging server and it is working as expected.
