### ISSUE TITLE
Actions Are Displaying Duplicate List

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#371]
When selecting the Actions option in Tracking, all Actions are duplicated.

**Comment by nmfujimoto** [comment]
![image](https://user-images.githubusercontent.com/50392020/98608266-a64ada80-229f-11eb-9fff-eaced5a244ad.png)

**Comment by Madhusmi** [comment]
@nmfujimoto Testing is Completed from QA end and it is working as expected.

**Comment by nmfujimoto** [comment]
@nfujimoto xCBL Schedule duplicating. Need to correct in production system due to title being the same.
