### ISSUE TITLE
Reschedule Actions Showing "Reschedule Arrival Date"

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#372]
The term "Arrival" date is only used for Return orders. All orders that are Original job type should display "Reschedule Delivery Date".

**Comment by nmfujimoto** [comment]
![image](https://user-images.githubusercontent.com/50392020/98608415-ff1a7300-229f-11eb-8316-1ff48c1600ad.png)

**Comment by Madhusmi** [comment]
@nmfujimoto Testing is Completed from QA end and it is working as expected.

**Comment by Madhusmi** [comment]
@nmfujimoto Testing completed in Staging as well as in Production server,It is working as expected
