### ISSUE TITLE
Add Purchase Order to Job Report Search

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#374]
Need to add Purchase Order field to the Search criteria in the Job Reports.

**Comment by nmfujimoto** [comment]
All to the generic search text field:
![image](https://user-images.githubusercontent.com/50392020/99346601-d539f100-2849-11eb-995f-291abfb15aca.png)

**Comment by Madhusmi** [comment]
@nmfujimoto Testing completed in QA server and it is working as expected.
