### ISSUE TITLE
DEV - Only Active Jobs Are Shown In Job Grid

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#396]
When selecting Archive for Jobs, no jobs are displayed in the Job Grid. Only Active jobs are found now.

**Comment by nmfujimoto** [comment]
![image](https://user-images.githubusercontent.com/50392020/101963612-f92bf080-3bc3-11eb-8e4a-578e84f06fae.png)

**Comment by Madhusmi** [comment]
@nmfujimoto Testing completed on Staging Server and it is working as expected.
