### ISSUE TITLE
DEV - Job Report Does NOT Populate Drop-Downs

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#401]
When selecting a customer in the drop-down control many of the other controls (Origin, Destination, Gateway Title, etc.) are NOT populated. If you select "All" for the customer control the other drop-downs still do not populate.

**Comment by nmfujimoto** [comment]
![image](https://user-images.githubusercontent.com/50392020/102139264-764ca500-3e12-11eb-99b5-f9775d9727fa.png)

**Comment by Madhusmi** [comment]
@nmfujimoto Testing completed on Staging server and it is working as expected.
