### ISSUE TITLE
Update The Job Report To Display Reschedule Actions In The Gateway Title Drop-down To Include "RS-" As A Prefix

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#409]
Need the ability to filter the Gateway Title drop-down in the Job Advance Report to allow a user to filter on Reschedule actions and select all. Adding a "RS-" to the beginning of the action's Gateway Title field will allow the user to filter on "RS-" to find all Reschedule actions.

**Comment by nmfujimoto** [comment]
First, update Program/Project Default Gateways to include a "RS-" in front of the Title for any Reschedule action, e.g. Accident would be RS-Accident, Consignee Initiated Change would be RS-Consignee Initiated

**Comment by Madhusmi** [comment]
@nmfujimoto Testing completed on QA Server and it is working as expected.
