### ISSUE TITLE
Not Displaying Schedule Action For Return Orders

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#413]
When trying to schedule a return order (AWC Home Delivery project Andrews SC location) the Schedule action is not displayed in the available list of actions. The Schedule action is missing when trying to use the ribbon actions in the dashboard and job grids. The Schedule action is also not displayed when viewing the job in the form view and right-clicking in the Tracking panel.

**Comment by Madhusmi** [comment]
@nmfujimoto Testing completed on QA and Staging server and it is working as expected.

**Comment by Madhusmi** [comment]
@nmfujimoto Testing completed on QA and Staging server and it is working as expected.

**Comment by nmfujimoto** [comment]
The Scheduled Pick Up action is not updating the Arrival Date Planned field, and the order is not removed from the Not Scheduled Return dashboard after adding the Scheduled Pick Up action. 

The Schedule Pick Up the "scheduled" flag for a return order, just like the Schedule Initial Appointment is for the original orders.

![image](https://user-images.githubusercontent.com/50392020/104870943-a221e580-58fe-11eb-858e-612c91bc778e.png)

**Comment by Madhusmi** [comment]
@nmfujimoto Testing Completed on Staging server and it is working as expected.
