### ISSUE TITLE
DEV - Dashboard After First Job Is Scheduled Additional jobs Do Not Show Schedule In Actions

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#416]
In the Dashboard details grid, after the first Return order is scheduled using the Actions in the ribbon and additional job that the user wants to schedule does not display the Schedule action. The user has to refresh the page to see Schedule as an option.

**Comment by Madhusmi** [comment]
@nmfujimoto Testing completed on Staging server and it is working as expected.
