### ISSUE TITLE
Calculate Storage Days Value When Creating NAV SO/PO

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#425]
When creating the SO/PO populate the field Storage in the Sales/Purchase Order Header. 

The Storage value should be an integer.

Storage = JobDeliveryDateTimeActual - JobOriginDateTimeActual

**Comment by prashantaggarwal1999** [comment]
Scripts needs to run for the same on Staging and Production is as follows:

IF NOT EXISTS(Select 1 From [dbo].[NAV000OrderMapping] Where NavColumn = 'Storage' AND [EntityName] = 'SalesOrder')
BEGIN
INSERT INTO [dbo].[NAV000OrderMapping] ([M4PLColumn]
      ,[NavColumn]
      ,[TableName]
      ,[EntityName]
      ,[SpecialHandling])
VALUES ('ISNULL(DATEDIFF(DAY, Job.JobOriginDateTimeActual, Job.JobDeliveryDateTimeActual),0)','Storage', 'Job', 'SalesOrder', 1)
END

IF NOT EXISTS(Select 1 From [dbo].[NAV000OrderMapping] Where NavColumn = 'Storage' AND [EntityName] = 'PurchaseOrder')
BEGIN
INSERT INTO [dbo].[NAV000OrderMapping] ([M4PLColumn]
      ,[NavColumn]
      ,[TableName]
      ,[EntityName]
      ,[SpecialHandling])
VALUES ('ISNULL(DATEDIFF(DAY, Job.JobOriginDateTimeActual, Job.JobDeliveryDateTimeActual),0)','Storage', 'Job', 'PurchaseOrder', 1)
END
