### ISSUE TITLE
Electrolux Program Vendor Location Replaced With AWC Location Value

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#427]
The Electrolux vendor location (SC13) was replaced with AWC vendor location (ANDREWS SC) when viewing the locations in the Electrolux Program. 

The above change to the vendor location stopped the ability to add Price/Cost charges to Electrolux jobs assigned to the SC13 location. 

The vendor location had to be removed from the Electrolux Vendors tab and re-added. Removing and adding the location removed all the Price/Cost charges for the SC13 location and they needed to be added again.

**Comment by prashantaggarwal1999** [comment]
@nmfujimoto This is not reproducible now, i guess it was the same issue which we had for the program.
