### ISSUE TITLE
Exceptions (AWC) Do Not Show Correct Form When Viewing

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#434]
The Exception records for damaged cargo are displayed in the Tracking records but when trying to view the Exception the Gateway Form is displayed with no information related to what the actual cargo item was damaged.

**Comment by nmfujimoto** [comment]
The Job Id 282015 is used in this example, and the exceptions were entered through BizMobl scanner using the API call JobCargos/CreateCargoException.

**Here is what a standard Exception for a damage would look like:**
![image](https://user-images.githubusercontent.com/50392020/106820696-a9502f80-6630-11eb-93af-12a3b324e993.png)


**When viewing an existing Exception record for a damaged item the form shows:**
![image](https://user-images.githubusercontent.com/50392020/106820771-cab11b80-6630-11eb-92f4-ccf36abd2c40.png)

**Comment by prashantaggarwal1999** [comment]
@kirtya please have a look into this issue.
