### ISSUE TITLE
OSD Report Error

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#436]
When generating an OSD Report the system took too long to return the results and displayed an error (see below in comments). 

After multiple tries, the report was generated by selecting the following criteria:
Customer: AWC
Gateway Titles: In Transit, On Hand, On Truck and Delivered
Delivery Dates: 2/3/2021 - 2/3/2021

**Comment by nmfujimoto** [comment]
![image](https://user-images.githubusercontent.com/50392020/106989438-062e1180-6727-11eb-9962-16ed5d77ac91.png)

![image](https://user-images.githubusercontent.com/50392020/106989456-0b8b5c00-6727-11eb-8cd1-c991c41c21c9.png)

**Comment by prashantaggarwal1999** [comment]
@kirtya please check this issue.

**Comment by Madhusmi** [comment]
@nmfujimoto Testing completed on Staging server and it is working as expected.
