### ISSUE TITLE
Replace the RTF Notes/Comments sections in the Job and Job Gateways with a Multi-line Textbox

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#438]
Remove all RTF controls in the UI and use multi-line textbox for the Notes tab and the Job Gateways comments fields.

**Comment by prashantaggarwal1999** [comment]
@nmfujimoto Application ran on the production to migrate the old data into the text columns.

**Comment by Madhusmi** [comment]
@nmfujimoto Testing completed on Staging server and working as expected.
