### ISSUE TITLE
DEV - New Projects Are Not Displayed

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#447]
In Staging database.

Added 4 new projects under AWC->RSI program:

- RSI Builder
- RSI Home Delivery
- PCS Builder 
- PCS Home Delivery

After saving each new project after creation, the system does not display the project under the AWC->RSI program. When I try to create the project again, the system tells me that the project already exists. 

I have tried using the browser refresh option but the new projects are not shown.

**Comment by Madhusmi** [comment]
@nmfujimoto Testing Completed on Staging environment and it is working as expected.
