### ISSUE TITLE
Reassign Active AWC Orders To Another Program

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#464]
There are roughly 99 active AWC orders currently assigned to the Program Id 10012 that need to be reassigned to Program Id 10028. Filter the orders using the column JobCarrierContract with the value "NMF".

Job Id's for a couple of the orders:
284513
284514
284515
284516

**Comment by prashantaggarwal1999** [comment]
[JobId's With JobCarrierContract = 'NMF'.xlsx](https://github.com/meridianww/M4PLBase/files/6059563/JobId.s.With.JobCarrierContract.NMF.xlsx)

@nmfujimoto done, here is the list of 99 jobs which got affected.
