### ISSUE TITLE
Update Cargo Quantity Values

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#465]
Related to #451

Update current cargo quantity columns with correct values based on what gateways the job currently has completed. 

Need to run a script to correct the data as the reports are producing skewed results.

**Comment by nmfujimoto** [comment]
In the example below, the job gateways of On Hand, Loaded on Truck and Delivered are completed but the cargo quantity values for each of the gateway statuses. 
![image](https://user-images.githubusercontent.com/50392020/109269153-f1421c80-77c0-11eb-85a9-63ae27114af0.png)

Cargo records:
![image](https://user-images.githubusercontent.com/50392020/109269164-f56e3a00-77c0-11eb-9bf9-b5fe16b3760f.png)

**Comment by prashantaggarwal1999** [comment]
@nmfujimoto Data correction is done for the Cargo and also added logic to read for available quantity if any of the quantity is missing.
