### ISSUE TITLE
Program Screen Does Not Refresh When Selecting Another Program

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#476]
When selecting different Programs/Projects in the Program module the Form does not change data. 

In the example below, the RSI Builder node is selected in the Program Tree but the form is still showing PCS Home Delivery project.

**Comment by nmfujimoto** [comment]
![image](https://user-images.githubusercontent.com/50392020/111100064-2316eb00-8504-11eb-9236-100e551cb724.png)

**Comment by Madhusmi** [comment]
****Scenarios what I have tested:****
1.Go to the Program Data grid.
2.Select first project of the AWC and RSI Program(example:"AKLOWES" and "RSI Builder) and verify the form data(whether it selected the current project "project code and Project Title".
3.Then select the second project and other projects.
4.Again select the first project and verify the form.
Existing Issue: When selecting different Programs/Projects in the Program module the Form does not change data.
After the Fix: When selecting different Programs/Projects in the Program module the Form showing the actual data.

**Comment by Madhusmi** [comment]
@nmfujimoto Testing Completed on Staging environment and it is working as expected.
