### ISSUE TITLE
AWC Home Delivery - Price/Cost Phoenix Location

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#492]
The Price/Cost for the Phoenix (PHOENIX AZ) and Las Vegas (LAS VEGAS-NV) locations are incorrect for AWC Home Delivery project. The Vendor location is "PHOENIX AZ" and "LAS VEGAS-NV but the Price/Cost locations are showing "PHOENIX AZ/R" and "LAS VEGAS-NV/R". 

Please remove the "/R".

**Comment by nmfujimoto** [comment]
![image](https://user-images.githubusercontent.com/50392020/112682421-5115fc80-8e2d-11eb-839e-063e7140e265.png)

**Comment by Madhusmi** [comment]
**Scenarios what I have tested:**
1.Go to the Program Data grid.
2.Select "Home Delivery" project of AWC Program.
3.Click Price/Cost codes.
4.Verify the Price/Cost for the Phoenix (PHOENIX AZ) and Las Vegas (LAS VEGAS-NV) locations.The Vendor location should be is "PHOENIX AZ" and "LAS VEGAS-NV.
Existing Issue: the Price/Cost for the Phoenix (PHOENIX AZ) and Las Vegas (LAS VEGAS-NV) locations are incorrect for AWC Home Delivery project. The Price/Cost locations are showing "PHOENIX AZ/R" and "LAS VEGAS-NV/R"(As per the business requirment for Vantity top,selling center,home delivery : no slash)
After the Fix: The Price/Cost locations are showing correct as "PHOENIX AZ" and "LAS VEGAS-NV.

**Comment by Madhusmi** [comment]
@nmfujimoto Testing Completed on Staging environment and it is working as expected.
