### ISSUE TITLE
Program Screen and Tree Are Incorrect

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#493]
The Program screen is showing records that are not currently selected. This is an ongoing issue and need to be fixed ASAP. This is greatly impacting configuring additional programs and projects.

**Comment by nmfujimoto** [comment]
We need to discuss this issue as the frustration is mounting on how this affects all other programs and billing.

In the screen capture below, AKLOWES project is currently selected, but the program screen is showing AKT project name and the Price location is showing the location code for SPAN which is another AWC project. 

**I Need This Fixed ASAP and All Data Correct.**

![image](https://user-images.githubusercontent.com/50392020/112683209-6ccdd280-8e2e-11eb-823a-12fa38713eb1.png)

**Comment by Madhusmi** [comment]
**Scenarios what I have tested:**
1.Go to the Program Data grid.
2.Select DO QA program.
3.Create a new project.
4.In Vendors tab do right click and select and click Map Vendor option.
5.Select and check the Unassigned Vendors checkbox and assign to Assigned Vendors.
6.Edit the Location code with "/Project name" and do update.
7.Go to the Price Codes tab and right click->Retrieve Location and assign Mapped Locations to Assigned Locations.
8.Repeat the same steps for Cost Codes.
9.Click a other project name.
10.Verify The Program screen is showing same project records.
Existing Issue: The Program screen is showing records that are not currently selected.
After the Fix: The Program screen is showing records that are currently selected.

**Comment by Madhusmi** [comment]
@nmfujimoto Testing Completed on Staging environment and it is working as expected.
