### ISSUE TITLE
Define security permission while creating ref roles

### ISSUE THREAD

**Issue by bharathrl** [meridianww/M4PLBase#5]
As a user of the application, I should be able to define the security for the ref roles I am adding.

1. User can add new ref roles from ref roles tab
2. After adding the mandatory details for creating the ref roles, enable the security tab and make it mandatory.
3. User will define the role security
4. User will save the role

Acceptance criteria
1. User should be able to add details to ref roles
2. All mandatory fields should be filled
3. Security details are mandatory and it must be added.
4. A contact can be mapped now or later
5. Details entered must be saved

Definition of Done
1.  All mandatory fields should be filled and saved.
2. Should pass regression test and unit testing.
3. Pass testing as per acceptance criteria.

**Comment by ChauhanNikhil** [comment]
Made changes to implement the required changes --
Functionality covered 1. When a user is creating a ref role, at the time of creation user should also define securtiy.
