### ISSUE TITLE
Previous text is stored in VOC Detail records

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#52]
When adding Detail records to the VOC questions (Customer Journey) the previous text stored in the Description field is displayed when you click on Add to add a new question.

**Comment by nmfujimoto** [comment]
Here is the information that I entered for Question #3 
![image](https://user-images.githubusercontent.com/50392020/64459506-e4050f80-d0ac-11e9-81df-51732cf54e33.png)

In this image I finished entering Question #3 and am clicking to add Question #24 
![image](https://user-images.githubusercontent.com/50392020/64459428-b28c4400-d0ac-11e9-89d4-bf9b22189c8b.png)

Entering the information for Question #4, the text in the Description area is from Question #3, and it should be blank since I only entered the information in the top group. 
![image](https://user-images.githubusercontent.com/50392020/64459477-d485c680-d0ac-11e9-8dc4-24907b4c552f.png)

**Comment by KamalAdhikary** [comment]
Implemented the requirement.
