### ISSUE TITLE
Drop down values for Customer role in DC Location

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#7]
As a user of the application, I should be able to view the drop-down values which will be coming from code and the type is Customer in Organisation ref roles.

1. Organization ref roles are defined in the organization module.
2. Each role is having a code,  type Customer and other details.
3. The Type which is Customer having the respective code will be displayed in the drop-down of Customer -> DC Location ->Customer Role.

Acceptance Criteria:
1. Each Type = Customer should have code values in Organisation ref roles
2. The code values should be reflected in Customer -> DC Location ->Customer Role.

Definition of Done
1.  All mandatory fields should be filled and saved.
2. Should pass regression test and unit testing.
3. Pass testing as per acceptance criteria.

**Comment by prashantaggarwal1999** [comment]
The stored procedure changes to get the Contact List on the basis of Customer Contact Entity.

**Comment by kirtya** [comment]
Introduce dropdown in UI with functionality to get the value from SP as respective to customer or vendor

**Comment by kirtya** [comment]
Write logic to update the Contact type as per company selection
