### ISSUE TITLE
EDI Table Identity Columns

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#72]
The database M4PL_Staging EDI 214 and 210 Tables do not have the ID column's Identity property set to Yes. The EDI210Invoice and EDI214ShipmentStatusHeader tables need to be updated with the ID column as an Identity auto-increment settings. 

Please verify all other EDI tables have identity values set to true for the ID columns in all M4PL databases.

**Comment by prashantaggarwal1999** [comment]
We have added a Column with name Id under the tables EDI210Invoice and EDI214ShipmentStatusHeader with Identity. This column is not the primary key for both the tables as Primary key is already present for the tables.

**Comment by nmfujimoto** [comment]
Team, I need to clarify this ticket. I would like the eshHeaderID and einInvoiceID columns in the two tables below to be the primary key with identity and increment set to Yes. 

Update the EDI214ShipmentStatusHeader table:
- Remove ID column
- Change eshHeaderID datatype to be bigint
- Set eshHeaderID as Primary Key
- Set eshHeaderID Identity to Yes with increment

Update the EDI210Invoice table:
- Remove ID column
- Change einInvoiceID datatype to be bigint
- Set einInvoiceID as Primary Key
- Set einInvoiceID Identity to Yes with increment

**Comment by prashantaggarwal1999** [comment]
Hi Nathan, We were under the impression that columns eshHeaderID and einInvoiceID has been added for any other purpose as these are the Varchar fields. We have corrected now, please check and confirm.
