### ISSUE TITLE
VOC Not Displaying Question (Description)

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#77]
The questions (Description) for the VOC surveys are not displayed anymore. Before the most recent update the entire question was displayed but not only the title is shown.

**Comment by nmfujimoto** [comment]
![image](https://user-images.githubusercontent.com/50392020/65718437-60f62a00-e058-11e9-8fee-c2e978b80f8f.png)

**Comment by prashantaggarwal1999** [comment]
Hi @nmfujimoto, There was some issue with the script which is used to get the question list, we have corrected that now and it is working as expected.
