### ISSUE TITLE
Vendors Are Mapped And Cannot Be Changed

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#85]
The MBCI program under the MBCI customer node contains two vendors that are mapped and should not be assigned to the program. When right-clicking and choosing Assign Vendors, the two vendors (Sierra Moving and Sameday Worldwide) should not be assigned and they do not appear in the Assign Vendor dialog screen. How can these vendors be removed?

**Comment by nmfujimoto** [comment]
The two vendors in the red square are incorrectly assigned to the MBCI program.
![image](https://user-images.githubusercontent.com/50392020/66871711-154ce700-ef59-11e9-8c45-517039841324.png)

When displaying the Assign Vendor screen the two vendors are not seen.
![image](https://user-images.githubusercontent.com/50392020/66871735-24cc3000-ef59-11e9-92ae-349ec1d533e6.png)

![image](https://user-images.githubusercontent.com/50392020/66871740-2ac21100-ef59-11e9-991b-936c5771b289.png)

**Comment by nmfujimoto** [comment]
Team,

It looks like both vendors are set to Archive which is why they are not displaying in the Assign Vendor screen. We need to remove these two vendors from the AWC and MBCI programs.

**Comment by prashantaggarwal1999** [comment]
Hi @nmfujimoto Please check this issue now, it seems to be fixed with the changes deployed on last Friday on 1010 and 3030 servers.
